name: Bug report
description: File a bug report
title: "[🐛BUG]: "
labels: [ bug ]
assignees:
  - 'N0tExisting'

body:
- type: checkboxes
  attributes:
    label: Is there an existing issue for this?
    description: Please search to see if an issue already exists for the bug you encountered.
    options:
    - label: I have searched the existing issues
      required: true

- type: textarea
  attributes:
    label: 'Current Behavior:'
    description: A concise description of what you're experiencing.
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: 'Steps To Reproduce:'
    description: Steps to reproduce the behavior.
    placeholder: |
      1. Go to '...'
      2. Click on '....'
      3. Scroll down to '....'
      4. See error
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: 'Expected Behavior:'
    description: A concise description of what you expected to happen.
    render: markdown
  validations:
    required: false

- type: textarea
  attributes:
    label: 'Environment'
    description: |
      examples:
        - Device: [e.g. iPhone6]
        - **OS**: [e.g. iOS, Windows]
        - **Browser**: [e.g. chrome, safari]
        - **Version**: [e.g. 22] _(browser version)_
    value: |
        - Device: 
        - OS: 
        - Browser: 
        - Version: 
    render: markdown
  validations:
    required: true

- type: textarea
  attributes:
    label: Anything else?
    description: |
      Links? References? Anything that will give us more context about the issue you are encountering!

      Tip\: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false

#"""
#**Describe the bug**
#A clear and concise description of what the bug is.
#
#**To Reproduce**
#Steps to reproduce the behavior:
#
#1. Go to '...'
#2. Click on '....'
#3. Scroll down to '....'
#4. See error
#
#**Expected behavior**
#A clear and concise description of what you expected to happen.
#
#**Screenshots**
#If applicable, add screenshots to help explain your problem.
#
#**Desktop (please complete the following information):**
#
#- OS: [e.g. iOS]
#- Browser [e.g. chrome, safari]
#- Version [e.g. 22]
#
#**Smartphone (please complete the following information):**
#
#- Device: [e.g. iPhone6]
#- OS: [e.g. iOS8.1]
#- Browser [e.g. stock browser, safari]
#- Version [e.g. 22]
#
#**Additional context**
#Add any other context about the problem here.
#"""
